# Modelando, visualizando e resolvendo sistemas lineares

Este capítulo está ligado ao seguintes objetivos didáticos do curos:
1. Resolver problemas de geometria espacial envolvendo conceitos de espaços vetoriais
1. Avaliar e resolver sistemas de equações lineares

Referência bibliográfica: [Jim Hefferon - Linear Algebra - 4th Edition](https://hefferon.net/linearalgebra/) - Chap. One, I, Chap. Three, III-IV

In [2]:
import numpy as np
import matplotlib.pyplot as plt

# Exercício 1
**Objetivo: Entender o problema de estimar custos de produção**

Uma doceria faz brigadeiros. Para fazer uma fornada com 20 brigadeiros, é preciso usar 40g de manteiga, uma lata (400g) de leite condensado e 20g de chocolate em pó.

O custo de cada ingrediente está na tabela:

Ingrediente | Custo por embalagem 
--- | ---
Leite condensado | R\$10,00 (lata de 400g) 
Manteiga | R\$15,00 (pote com 200g)
Chocolate em pó |R\$18,00 (caixa com 200g)

Para calcular o custo de uma fornada de brigadeiros, precisamos multiplicar o custo de cada embalagem pela quantidade dele que foi utilizada, e então somar os resultados.

Complete o código abaixo para estimar quanto custa fazer uma fornada de 20 brigadeiros.

In [3]:
# Resolva o exercício aqui
custo_por_ingrediente = [10, 15, 18] # O que esses números representam?
quantidades = [1, 1/5, 1/10]
custo_total = 0
for n in range(len(custo_por_ingrediente)): # O que precisa ser feito para cada ingrediente?
    continue
    
print(custo_total)

0


# Exercício 2
**Objetivo: Usar soma e multiplicação ponto a ponto de vetores**

No primeiro exercício, fizemos um laço explícito para multiplicar duas listas e somar os resultados ponto a ponto. A equação que implementamos foi:

$$
C = \sum_{n=0}^{N-1} I[n] Q[n],
$$

onde $\boldsymbol{I}$ guarda os ingredientes e $\boldsymbol{Q}$ guarda as quantidades utilizadas.

Se usarmos vetores ao invés de listas, podemos usar a seguinte operação:
$$
C =  \sum_{n=0}^{N-1} I \odot Q.
$$

O operador $\odot$ significa "produto ponto-a-ponto" (*pointwise multiplication*), e é definido como:
$$
(I \odot Q)[n] = I[n] Q[n]
$$

Quando multiplicamos dois vetores de numpy, realizamos a operação $\odot$ entre eles. Veja, por exemplo:

In [ ]:
a = np.array([1, 2, 7])
b = np.array([3, 2, 1])
c = a * b
print(c)

Também, podemos usar a operação `np.sum(x)` para encontrar a soma de todos os elementos do array `x`.

Com base nisso, re-escreva abaixo o código do exercício 1 usando os operadores de multiplicação ponto-a-ponto e a função `np.sum()`, de forma que não seja necessário usar laços em seu código.

In [ ]:
custo_por_ingrediente = np.array([10, 15, 18]) # O que esses números representam?
quantidades = np.array([1, 1/5, 1/10])



14.8


# Exercício 3
**Objetivo: modelar a soma de produtos como um produto interno**

A operação $\sum_n x[n]y[n]$, que fizemos nos exercícios 1 e 2, pode ser interpretada como uma soma dos elementos de $\boldsymbol{x}$ ponderada pelos elementos correspondentes em $\boldsymbol{y}$. Essa operação é muito comum, e é chamada de "produto interno" (*inner product*). O produto interno é definido como:

$$
<x, y> = \sum_n x[n]y[n] = \sum_n x \odot y
$$

Em Numpy, a função que calcula o produto interno de dois vetores é `np.inner(x, y)`, então poderíamos resolver os exercícios 1 e 2 usando:

In [ ]:
custo_total = np.inner(custo_por_ingrediente, quantidades)
print(custo_total)

14.8


Vamos agora expandir nossa doceria. Além de brigadeiros, vamos adicionar *ganache* no cardápio.

Para fazer um pote de ganache, é preciso usar 40g de manteiga, 40g de chocolate e 200mL de creme de leite. Uma caixinha de 200mL de creme de leite custa R\$2,80. Nossa tabela de ingredientes então fica:

Ingrediente | Custo por embalagem 
--- | ---
Leite condensado | R\$10,00 (lata de 400g) 
Manteiga | R\$15,00 (pote com 200g)
Chocolate em pó |R\$18,00 (caixa com 200g)
Creme de leite | R\$2,80 (caixa com 200mL)

Em nosso modelo, gostaríamos de usar um único vetor `custo_por_ingrediente` tanto para o brigadeiro quanto para o ganache, e passamos a ter um vetor `quantidades_brigadeiro` para o brigadeiro e um vetor `quantidades_ganache` para o ganache.

Complete a solução abaixo para calcular o custo de cada uma das fornadas de doce.

1. Complete a definição dos vetores `quantidades_brigadeiro` e `quantidades_ganache`. Como podemos fazer para representar o fato de que um brigadeiro não usa creme de leite e que um ganache não usa manteiga?
2. Como a lista de vetores `custos_totais` é calculada? Qual é o conteúdo dela?
3. Adicione o "doce de leite" ao cardápio. A receita dele é muito simples: deixamos uma lata de leite condensado ferver na panela de pressão por 40 minutos. Lembre-se de fazer essa adição sem alterar o código abaixo da linha marcada.
4. Adicione o "doce de coco" ao cardápio. Uma fornada de 20 doces usa 200g de leite condensado e 250g de coco ralado. O pacote de 1kg de coco ralado custa R$35,00.  Lembre-se de fazer essa adição sem alterar o código abaixo da linha marcada.

In [ ]:
custo_por_ingrediente = np.array([10, 15, 18, 2.8])

quantidades_brigadeiro = np.array([1, 0.2, 0.1, 0]) # Complete esse
quantidades_ganache = np.array([0, 0.2, 0.2, 1]) # Complete esse

quantidades = [quantidades_brigadeiro, quantidades_ganache]

# Não modifique nada abaixo desta linha
custos_totais = []
for idx, q in enumerate(quantidades):
    custos_totais.append (np.inner(custo_por_ingrediente, q))
print(custos_totais)

[14.8, 9.4]


# Exercício 4
**Objetivo: Usar matrizes ao invés de listas de vetores**

No exercício 3, usamos um vetor para representar cada uma das quantidades de ingredientes. Ao invés de fazer isso, podemos usar matrizes, que são essencialmente "vetores de vetores".

Assim como tínhamos usado uma lista para inicializar os elementos de um vetor, vamos usar listas de listas para inicializar os elementos de uma matriz:

In [ ]:
a = np.array([ [1, 2, 3], [4, 5, 6] ])
print(a)
print(a[0,1])
print(a.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


Veja que todas as listas passadas têm que ter o mesmo tamanho, o que permite gerar essa estrutura retangular com linhas e colunas.

Vamos praticar o uso de matrizes.

Crie duas matrizes:
1. A matriz de receitas $\boldsymbol{X}$, que tem um linha para cada receita da doceria e uma coluna para cada ingrediente usado, isto é, $x[i,j]$ representa a quantidade do ingrediente $j$ na receita $i$.
2. A matriz de custos $\boldsymbol{Y}$, que tem apenas uma coluna e cada linha representa o custo de cada ingrediente, na mesma ordem usada na matriz $\boldsymbol{X}$.
3. Veja que $\boldsymbol{X}$ deveria ser uma matriz com 4x5 (isto é, 4 linhas e 5 colunas), e $\boldsymbol{Y}$ deveria ser uma matriz 5x1, isto é, com 5 linhas e 1 coluna. Use o método `shape` para confirmar as dimensões das matrizes.

In [ ]:
X = np.array( [ [1, 0], [0.2, 0.2], [0.1, 0.2], [0, 1] ])
Y = np.array( [ [12], [0.12], [0.9], [2.8] ])
print(X)
print(Y)
print(Y.shape)

[[1.  0. ]
 [0.2 0.2]
 [0.1 0.2]
 [0.  1. ]]
[[12.  ]
 [ 0.12]
 [ 0.9 ]
 [ 2.8 ]]
(4, 1)


# Exercício 5
**Objetivo: Usar multiplicação matricial para o modelo mais compacto**

Uma operação importante que vamos usar hoje é a *multiplicação matricial* (*dot product*). A notação matemática para esta operação é:
$$
\boldsymbol{Z} = \boldsymbol{X} \boldsymbol{Y}
$$

Essa operação cria uma matriz $\boldsymbol{Z}$ tal que o elemento $z[i,j]$ é o produto interno entre a i-ésima linha de $\boldsymbol{X}$ e a j-ésima coluna de $\boldsymbol{Y}$, isto é:

$$
z[i,j] = <\boldsymbol{X[i,:]}, \boldsymbol{Y[:,j]}> = \sum_{n=0}^{N-1} x[i,n] y[n,i]
$$

Veja por exemplo:
$$ \boldsymbol{x} = 
\begin{bmatrix}
    1 & 2\\
    3 & 4
\end{bmatrix}
$$

$$ \boldsymbol{y} = 
\begin{bmatrix}
    -1 \\
    -2 
\end{bmatrix}
$$

$$ \boldsymbol{z} = 
\begin{bmatrix}
    -1 \times 1 + -2 \times 2 \\
    -1 \times 3 + -2 \times 4
\end{bmatrix}
= 
\begin{bmatrix}
    -1 -4 \\
    -3 -8
\end{bmatrix}
= 
\begin{bmatrix}
    -5 \\
    -11
\end{bmatrix}
$$


A multiplicação matricial pode ser representada em Python usando o operador `@` ou então a função `np.dot()`:

In [ ]:
x_ = np.array([ [1, 2], [3, 4] ])
y_ = np.array([ [-1], [-2]])
z_ = x_ @ y_
print(z_)
z_ = np.dot(x_, y_)
print(z_)

[[ -5]
 [-11]]
[[ -5]
 [-11]]


Para que a operação de multiplicação matricial seja possível, é preciso que haja tantas colunas em $X$ quanto linhas em $Y$, mas o número de linhas de $X$ e o de colunas em $Y$ é livre. Em outras palavras:

* $X \in \mathbb{R}^{i \times N}$
* $Y \in \mathbb{R}^{N \times j}$
* $Z \in \mathbb{R}^{i \times j}$

Usamos uma notação $M \in \mathbb{R}^{A \times B}$ (geralmente isso é lido como "M pertence a R-A por B") para significar que a matriz $M$ tem $A$ linhas e $B$ colunas. Essa notação vem da ideia do conjunto dos números reais ($\mathbb{R}$) - lembre-se que, quando $x$ é um número real qualquer, dizemos que "x pertence aos números reais, ou $x \in \mathbb{R}$. Da mesma forma, quando um vetor $v$ tem $N$ elementos, dizemos que ele pertence a "R-N$, ou, $v \in \mathbb{R}^N$.

1. Calcule (manualmente, no papel) o valor da matriz $z$ abaixo, e, após, confirme seu resultado usando Python. 
$$
z = x y\\

x =
\begin{bmatrix}
    0 & 1\\
    2 & 3
\end{bmatrix}\\ 

y =
\begin{bmatrix}
    2 \\
    1
\end{bmatrix}
$$

2. Se temos as matrizes $X$, com uma linha por receita e uma coluna por ingrediente, e $A$, com uma linha por ingrediente e apenas uma coluna, (a) qual deve ser a dimensão da matriz $Y=XA$? (b) O que cada elemento de $Y$ representa?

3. Vamos supor que temos uma outra opção de mercado, com outros custos para os ingredientes. O que aconteceria com a interpretação dos elementos da matriz $Y$ do ítem acima se os preços do novo mercado fossem representados como uma nova coluna na matriz $A$?


# Exercício 6
**Objetivo: Interpretar a multiplicação matricial como um sistema com entradas e saídas**

Nos exercícios acima, fizemos uma mutiplicação matricial. Partimos da matriz $X$, (receitas por ingrediente), e multiplicamos pela matriz $A$ (ingrediente por custo), gerando a matriz $Y$ (receitas por custo), ou: $Y = XA$.

A multiplicação matricial poderia ser interpretada como uma função escrita em Python parecida com:

    def calcular_custos(receitas, custos):
        # Executa multiplicacao matricial
        custos = receitas @ custos
        return custos

---

1. A doceria gostaria de que seu preço de venda fosse sempre 10% superior ao custo com ingredientes. Faça um programa que calcula o preço de venda de cada receita usando multiplicações matriciais. Qual é o preço de venda de cada receita?
3. A doceria decidiu fazer dois kits para vender: o kit A, que tem 100 brigadeiros e 1 pote de ganache, e o kit B, que tem 10 brigadeiros, 10 doces de coco e 2 potes de ganache. Faça um programa que calcula o preço de venda de cada kit usando multiplicações matriciais. Qual é o preço de venda de cada kit?
4. Um cliente fez um pedido de dois kits A e três kits B. Usando apenas multiplicações matriciais (e o mesmo processo que fizemos ao longo deste exercício) qual é o preço total deste pedido?
